# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 726378d394711daa37901486be9601f339aa01376d425d7e5aebb7900ad74eb6061cd378ff16cf3754ea85f0d85ab0c2ac1550db5373205dbf74fe43a34dc9dd

test:
  secret_key_base: 9042328be762f310e1b2426f9c643881aded9c2a3a334539ef9793eda8e1d96d7cc073c8e2c3554f368f69ebca071ec56c0c08df8a8e6ddad4fc6a1ed35a44fc

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
